trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    sudo apt-get update
    sudo apt-get install -y aria2  # نصب ابزار aria2
    python -m venv env
    source env/bin/activate
    pip install requests
    python aria2_server.py  # اجرای اسکریپت
  displayName: 'Run Aria2 Server'
